# Create dataframe with bias outcomes -------------------------------------

outcomes <- tibble(
  question_id = rep(c("same_model_tool",
                  "report_random_allocation_tool",
                  "describe_random_component_tool",
                  "appropriate_randomization_tool",
                  "report_base_chars_tool",
                  "similar_base_chars_tool",
                  "adjust_confound_tool",
                  "describe_allocation_tool",
                  "seqgen_blind_tool",
                  "appropriate_conceal_tool",
                  "describe_housing_tool",
                  "cages_random_tool",
                  "mention_blinding_tool",
                  "blinding_general_tool",
                  "blinding_explicit_tool",
                  "blinding_general_appropriate_tool",
                  "blinding_explicit_appropriate_tool",
                  "mention_random_tool",
                  "mention_random_general_tool",
                  "describe_random_outcome_selection_tool",
                  "random_general_appropriate_tool",
                  "random_explicit_appropriate_tool",
                  "mention_blinding_outcome_tool",
                  "blinding_outcome_general_tool",
                  "blinding_assessors_explicit_tool",
                  "blinding_outcome_general_appropriate_tool",
                  "blinding_outcome_explicit_appropriate_tool",
                  "describe_dropout_tool",
                  "report_num_started_tool",
                  "report_num_analyzed_tool",
                  "start_analyzed_match_tool",
                  "dropout_exists_tool",
                  "number_reason_dropout_tool",
                  "number_reason_equal_tool",
                  "imputation_tool",
                  "preregistration_tool",
                  "all_results_published_tool",
                  "endpoint_defined_tool",
                  "outcome_protocol_match_tool",
                  "endpoint_study_match_tool",
                  "prereg_conducted_tool",
                  "coi_statement_tool",
                  "coi_reported_tool",
                  "treatm_dissolved_tool",
                  "indiv_housing_tool",
                  "cages_unit_tool",
                  "added_animals_tool"), each = 2),
  response = rep(c("Yes","No"), length(question_id)/2),
) %>% 
  mutate(outcome = case_when(question_id == "same_model_tool" & response == "No" ~ "High",
                             question_id == "report_random_allocation_tool" & response == "No" ~ "Unclear",
                             question_id == "describe_random_component_tool" & response == "No" ~ "Unclear",
                             question_id == "appropriate_randomization_tool" & response == "No" ~ "High",
                             question_id == "appropriate_randomization_tool" & response == "Yes" ~ "Low",
                             question_id == "report_base_chars_tool" & response == "No" ~ "Unclear",
                             question_id == "similar_base_chars_tool" & response == "Yes" ~ "Low",
                             question_id == "adjust_confound_tool" & response == "No" ~ "High",
                             question_id == "adjust_confound_tool" & response == "Yes" ~ "Low",
                             question_id == "describe_allocation_tool" & response == "No" ~ "Unclear",
                             question_id == "seqgen_blind_tool" & response == "Yes" ~ "Low",
                             question_id == "appropriate_conceal_tool" & response == "No" ~ "High",
                             question_id == "appropriate_conceal_tool" & response == "Yes" ~ "Low",
                             question_id == "describe_housing_tool" & response == "No" ~ "Unclear",
                             question_id == "cages_random_tool" & response == "No" ~ "High",
                             question_id == "cages_random_tool" & response == "Yes" ~ "Low",
                             question_id == "mention_blinding_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_explicit_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_general_appropriate_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_general_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "blinding_explicit_appropriate_tool" & response == "No" ~ "High",
                             question_id == "blinding_explicit_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "mention_random_tool" & response == "No" ~ "Unclear",
                             question_id == "random_general_appropriate_tool" & response == "No" ~ "Unclear",
                             question_id == "random_general_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "random_explicit_appropriate_tool" & response == "No" ~ "High",
                             question_id == "random_explicit_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "mention_blinding_outcome_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_assessors_explicit_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_outcome_general_appropriate_tool" & response == "No" ~ "Unclear",
                             question_id == "blinding_outcome_general_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "blinding_outcome_explicit_appropriate_tool" & response == "No" ~ "High",
                             question_id == "blinding_outcome_explicit_appropriate_tool" & response == "Yes" ~ "Low",
                             question_id == "report_num_started_tool" & response == "No" ~ "Unclear",
                             question_id == "report_num_analyzed_tool" & response == "No" ~ "Unclear",
                             question_id == "start_analyzed_match_tool" & response == "No" ~ "High",
                             question_id == "start_analyzed_match_tool" & response == "Yes" ~ "Low",
                             question_id == "dropout_exists_tool" & response == "No" ~ "Low",
                             question_id == "number_reason_dropout_tool" & response == "No" ~ "Unclear",
                             question_id == "number_reason_equal_tool" & response == "Yes" ~ "Low",
                             question_id == "imputation_tool" & response == "No" ~ "High",
                             question_id == "imputation_tool" & response == "Yes" ~ "Low",
                             question_id == "all_results_published_tool" & response == "No" ~ "High",
                             question_id == "all_results_published_tool" & response == "Yes" ~ "Unclear",
                             question_id == "outcome_protocol_match_tool" & response == "No" ~ "High",
                             question_id == "outcome_protocol_match_tool" & response == "Yes" ~ "Low",
                             question_id == "endpoint_study_match_tool" & response == "No" ~ "High",
                             question_id == "prereg_conducted_tool" & response == "No" ~ "High",
                             question_id == "prereg_conducted_tool" & response == "Yes" ~ "Low",
                             question_id == "coi_statement_tool" & response == "No" ~ "Unclear",
                             question_id == "coi_reported_tool" & response == "No" ~ "Low",
                             question_id == "coi_reported_tool" & response == "Yes" ~ "High",
                             question_id == "treatm_dissolved_tool" & response == "No" ~ "Low",
                             question_id == "indiv_housing_tool" & response == "Yes" ~ "Low",
                             question_id == "cages_unit_tool" & response == "No" ~ "High",
                             question_id == "cages_unit_tool" & response == "Yes" ~ "Low",
                             question_id == "added_animals_tool" & response == "No" ~ "Low",
                             question_id == "added_animals_tool" & response == "Yes" ~ "High",
                             )) %>% 
  mutate(bias_type = c(rep("sequence_allocation", 8),
                       rep("baseline_characteristics", 6),
                       rep("allocation_concealment", 6),
                       rep("random_housing", 4),
                       rep("blinded_experiment_conduct", 10),
                       rep("random_outcome_assessment", 10),
                       rep("blind_outcome_assessment", 10),
                       rep("incomplete_outcome_data", 16),
                       rep("selective_reporting", 12),
                       rep("other_funder_influence", 4),
                       rep("other_analysis_unit", 6),
                       rep("other_new_animals", 2))) %>% 
  # mutate(bias_type = case_when(question_id = "same_model_tool" ~ "sequence_allocation"))
  rename(response_id = response) %>% 
  mutate(response = interaction(question_id, response_id))

data.table::fwrite(outcomes, file = here::here("data","outcomes.csv"), sep = ",")
