
# Information section -----------------------------------------------------

about <- tabItem(
  tabName = "about",
  fluidPage(
    h1("Welcome"),
    br(),
    shiny::markdown(
      "
      ## CAMARADES Risk of Bias app
      
      Welcome! Here you will find information on the different types of bias present in preclinical experimental studies. 
      Our goal is to provide a comprehensive resource on how different types of bias present in the literature and what kind of questions 
      can be asked to evaluate risk of bias in preclinical studies. 
      
      Navigate through the different sections on the left-side panel to:
      
      - learn all about the different aspects of bias and how to assess risk of bias in preclinical studies
      
      - conduct a risk of bias assessment yourself on a study of your choice. 
      
      - export the results of your assessment and visualize them using 'traffic-light' plots.
      
      <br>
      
      <br>
      
      ## About the team
      
      The CAMARADES Collaborative Approach to Meta-Analysis and Review of Animal Data from Experimental Studies group 
      specialize in performing systematic review and meta-analysis of data from experimental studies. If you have questions about this resource, please email us at: xxx
      "
      ),
    br(),
    br(),
    br(),
    shiny::markdown(
      "
      ## Acknowledgements
      
      The assessment tool implemented in this app is based on the SYRCLE's risk of bias tool for animal studies (Hooijmans et al., 2014). 
      The visualizations are created using tools from the R package `robvis` (McGuinness and Higgins, 2020).
      
      <br>
      
      Hooijmans, C.R., Rovers, M.M., de Vries, R.B. et al. SYRCLE’s risk of bias tool for animal studies. BMC Med Res Methodol 14, 43 (2014). https://doi.org/10.1186/1471-2288-14-43
      
      McGuinness, LA, Higgins, JPT. Risk-of-bias VISualization (robvis): An R package and Shiny web app for visualizing risk-of-bias assessments. Res Syn Meth. 2020; 1- 7. https://doi.org/10.1002/jrsm.1411
      "
    )
  )
)

# Sequence allocation -----------------------------------------------------

sequence_allocation <- tabItem(
  tabName = step_ids[[1]],
  h1("1. Sequence allocation"),
  "Sequence allocation refers to the allocation of animals to the experimental and 
  control groups. This should be adequately generated, but also adequately applied, with 
  appropriate randomization. This item assesses whether the methodology used to generate
  the allocation sequence is described in sufficient detail to allow an assessment 
  whether it should produce comparable groups. The following signaling questions may be
  used to guide assessment of this domain.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Did the authors compare two cohorts of the same genetic model?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("The comparison of cohorts of different genetic models, irrespective of subsequent 
        randomization procedures, indicates a high risk of bias.")
      )
    ),
    tabBox(
      title = ("Do the authors report random allocation to group?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If allocation to group is not reported to be random, it is unclear whether groups were
          randomized, even if this was part of experimental procedures.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Did the authors describe a random component in the sequence generation process?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("It is generally not sufficient to mention randomization alone, without describing
          the method used to achieve random sequence allocation.")
      )
    ),
    tabBox(
      title = ("Was the method chosen appropriate to achieve random sequence allocation?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Referring to a random number table or using a computer random number generator
        are adequate approaches to including a random component in the sequence generation
        process. Examples of a non-random approach may include: allocation by the investigator's
        preference/judgement, allocation based on the results of laboratory tests, allocation
        by availability of the intervention, sequence generated by some rule based on animal or
        cage number, and sequence generated by odd or even date of birth.")
        )
      )
    )
  )


# Baseline characteristics ------------------------------------------------

baseline_characteristics <- tabItem(
  tabName = step_ids[[2]],
  h1("2. Baseline characteristics"),
  "This item refers to the distribution of relevant baseline characteristics for the different
  treatment groups. Depending on whether this distribution is balanced or unequal, 
  different actions are recommended to investigators in order to avoid bias.
  It is important to note that the number and type of baseline characteristics 
  are dependent on the review question. Before starting their risk of bias assessment, 
  reviewers need to discuss which baseline characteristics need to be comparable between the groups.
  A description of baseline characteristics and/or confounders usually contains: (1) the sex, age and 
  weight of the animals, and (2) baseline values of the outcomes which are of interest in the study/",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Do the authors report the baseline characteristics (age, sex AND weight) 
               in the methods, results or supplements?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If any of the predefined baseline characteristics are not described anywhere in 
        the study, the risk of bias remains unclear. This holds even if the authors state 
        that groups did not differ at baseline.")
      )
    ),
    tabBox(
      title = ("Are the groups similar at baseline with respect to age, sex and weight?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Observed differences in baseline characteristics between groups might point to
          high risk of bias if not properly accounted for in the analysis.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Did the authors adjust the statistical analyses for confounders?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In the case of unequal distribution of baseline characteristics between groups, the
        risk of bias is declared low if the investigators adjust for it in the statistical
        analyses, and high if not.")
      )
    )
  )
)



# Allocation concealment --------------------------------------------------

allocation_concealment <- tabItem(
  tabName = step_ids[[3]],
  h1("3. Allocation concealment"),
  "Allocation concealment refers to the blinding of participants and personnel, which 
  can be a source of performance bias. In the case of animal studies, this refers predominantly 
  to the personnel involved in the experiments. This includes both researchers, as well as animal
  caregivers, as the handling of animals during the study while knowing the treatment condition
  could cause behavioral changes influencing the study results.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Was the allocation (randomization) procedure described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Lack of information on how the procedure of sequence allocation occurred is indicative
          of unclear risk of bias in this domain.")
      )
    ),
    tabBox(
      title = ("Was sequence generation conducted by someone not involved in the experiment?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In cases where sequence allocation is done by third-parties not involved in the
          experimental study, concealment is deemed appropriate and indicates a low risk of 
          performance bias.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Was the allocation concealment appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In addition to third-party group allocation, another example of appropriate concealment
          includes the use of properly safeguarded envelopes e.g. sequentially numbered
          opaque, sealed envelopes. On the other hand, inadequare approaches to concealment include: 
          open randomization schedule, envelopes without proper safeguard, alternation or rotation,
          allocation based on date of birth or animal number, or any other explicitly unconcealed
          procedure of a non-random approach.")
      )
    )
  )
)


# Random housing ----------------------------------------------------------

random_housing <- tabItem(
  tabName = step_ids[[4]],
  h1("4. Random housing"),
  "This item refers to the housing conditions of animals during the experiment. As housing conditions 
  (such as lighting, humidity,  temperature, etc.) are known to 
  influence study outcomes (such as certain biochemical parameters and behavior), 
  it is important that the housing of these animals is randomized or, in other words, 
  comparable between the experimental groups in order to reduce the risk of performance bias.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Was housing described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Lack of information on the housing conditions of animals during the
          study signals an unclear risk of bias, as it remains difficult to ascertain
          if these were handled appropriately.")
      )
    ),
    tabBox(
      title = ("Were cages placed randomly within the housing facility?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("For example, animals from different treatment groups should not be housed 
        per group on different shelves or in different rooms as the animals on the 
        top shelf experience a higher room temperature than animals on the lowest shelf, 
        and the temperature of the room may influence the toxicity of pharmacological 
        agents. When cages are not placed randomly (e.g., when animals are housed per group 
        on different shelves), moreover, it is possible for the investigator to predict 
        the allocation of the animals to the various groups, which would indicate 
        performance bias.")
      )
    )
  )
)



# Blinding ----------------------------------------------------------------

blinded_conduct <- tabItem(
  tabName = step_ids[[5]],
  h1("5. Blinded conduct of the experiment"),
  "This item evaluates whether the personnel (caregivers and/or investigators) were 
  blinded from knowledge on which intervention each animal received during the experiment.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Lack of explicit statements on blinding of investigators and/or caregivers could 
        indicate an unclear risk of bias, given that insufficient information is available 
          to evaluate the procedure.")
      )
    ),
    tabBox(
      title = ("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Examples of appropriate blinding methods in this context include: using ID cards of 
        individual animals or cage/animal labels that are coded and identical in appearance, using 
        sequentially numbered drug containers are identical in appearance, specifying similar circumstances 
        during the intervention in both groups, and randomizing housing conditions of the animals during 
        the experiment (see section Random Housing). Inappropriate blinding procedures could include: differently
        colored cage labels per group, expected differences in visible effects between control and experimental 
        groups, non-randomized housing conditions and having the same individual(s) prepare, conduct and analyse
        the experiment. Inappropriate blinding could be in play when the intervention circumstances are not similar
        betwen groups, such as different timing of placebo/drug administration or using different instruments to
        carry out the same experimental procedures in the two groups.")
      )
    )
  )
)


# Random outcome assessment -----------------------------------------------

random_outcome <- tabItem(
  tabName = step_ids[[6]],
  h1("6. Random outcome assessment"),
  "This item refers to determining whether or not animals were selected at random 
  for outcome assessment, regardless of the allocation to the experimental or control group. 
  For instance, when animals are sacrificed per group at various time points during the day, 
  the scientist concerned might interpret the results of the groups differently because she 
  or he can foresee or predict the allocation. Another reason to select animals at random for outcome 
  assessment is the presence of circadian rhythms in many biological processes. Not selecting the animals 
  for outcome assessment at random might influence the direction and magnitude of the effect.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is randomization mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("It is possible that authors provide a general statement in the beginning of the Methods section 
        stating that all procedures were conducted in a random manner. In this case, this general statement can be considered 
        to include specific outcome assessments. Neverthtless, the methods used to determine random outcome assessment
        still need to be described in order to achieve a low risk of bias in this domain.")
      )
    ),
    tabBox(
      title = ("Is the method of randomization described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Examples of appropriate (i.e. random) sequence generation methods include referring to a 
          random number table or using a computer random number generator. On the other hand, examples of
          inappropriate (non-random) sequence generation methods could be allocation by investigator's judgement or
          preference, allocation based on a series of tests or availability of intervention, or determining the sequence
          based on other arbitrary rules such as odd/even date of birth or cage number.")
      )
    )
  )
)


# Blinded outcome assessment ----------------------------------------------

blind_outcome <- tabItem(
  tabName = step_ids[[7]],
  h1("7. Blinded outcome assessment"),
  "This refers to evaluating the methods used for outcome assessment in both the experimental and
  control groups, with regard to adequate blinding. This item should be assessed separately
  for each main outcome.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Similar to random outcome assessment, the goal of this signaling question is to
          assess whether sufficient information is provided on adequately blinding outcome
          assessors.")
      )
    ),
    tabBox(
      title = ("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("As with blinding of experiment conduct, appropriate concealment methods include
          the use of equipment such as ID cards, labels or drug containers that are coded and identical in 
          appearance between groups, as well as randomizing housing conditions. Respectively,
          inappropriate approaches to assessor blinding could include visibly different labels 
          (e.g. colored) per group, non-randomized housing conditions, or differences in the 
          circumstances under which intervention is administered (see also Item 5).")
      )
    )
  )
)

# Attrition ---------------------------------------------------------------

incomplete_outcome <- tabItem(
  tabName = step_ids[[8]],
  h1("8. Incomplete outcome data"),
  "This item evaluates whether incomplete outcome data were adequately addressed and the
  risk of bias associated with that.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = space_after("Is there a section specifically describing drop-outs or mortality?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In order to be able to assess risk of bias in this domain, explicit description 
        of attrition in the study, such as mentioning drop-out and mortality should be
          provided.")
      )
    ),
    tabBox(
      title = ("Do the numbers of animals that started the experiment and were analysed match?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If these numbers match, no drop-out may be assumed, which is in turn indicative of a
          low risk of bias. In case these numbers differ, unexplained drop-out rates would
          suggest a high risk of bias.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Are the number and the reason for drop-out/death specified and equally distributed per group?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In the presence of missing data, it is important that the authors clearly state
          the numbers related to drop-out across groups, as well as the reasons, so potential
          group differences may be determined.")
      )
    ),
    tabBox(
      title = space_after("Were missing data imputed using appropriate statistical methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In case missing data are present and the numbers/reasons are not balanced
          across groups, the use of appropriate statistical methods for imputation should
          be considered. Failure to address these imbalances could lead to a high risk of bias.")
      )
    )
  )
)


# Selective outcome reporting ---------------------------------------------

selective_reporting <- tabItem(
  tabName = step_ids[[9]],
  h1("9. Selective outcome reporting"),
  "This item evaluates reporting bias in a study.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Was the study protocol available and published prior to the study results? "),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("While registration of animal intervention protocols might not be standard practice 
          for all yet, this is becoming increasingly more important, and a critical element
          of bias assessments in preclinical studies.")
      )
    ),
    tabBox(
      title = "Were results reported for all experiments outlined in the methods section and is the study is free of explicitly unpublished results?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If there is indication of explicitly unpublished results (e.g.'data not shown'),
          there is a significant risk of reporting bias. Even in the case of reporting results
          from all experiments described in the methods, the risk of reporting bias could remain
          unclear, given that it is difficult to judge the planned analysis without a
          preregistered protocol.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Do all the outcomes in the protocol and in the final report match or were deviations reported?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If no primary endpoint was defined in the protocol, a match between study reporting and all pre-specified 
          outcomes is expected. If this is not the case, and no explicit deviations were reported,
          a high risk of bias is present.")
      )
    ),
    tabBox(
      title = "Were all pre-specified outcomes conducted and reported as planned or were deviations explained?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Even when the primary endpoint in the protocol matches the main finding of the final
          report, any deviations from the protocol should be clearly stated to avoid a high risk 
          of bias. Similarly, a high risk of bias is present if one or more of the outcomes reported 
          in the final study were not pre-specified. This is subject to evaluation if clear 
          justification may be provided (e.g. unexpected adverse effects).")
      )
    )
  )
)


# Other bias --------------------------------------------------------------

funder_influence <- tabItem(
  tabName = step_ids[[10]],
  h1("10.1 Inappropriate influence of funders"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Were sources of funding reported?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Inappropriate influence of funders is a possibility, if no information
          on the matter is available, which means the risk of bias status remains unclear.")
      )
    ),
    tabBox(
      title = tab_title("Did the authors report a conflict of interest?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Author-reported conflicts of interest could represent significant sources
          of bias in a study.")
      )
    )
  )
)

analysis_unit <- tabItem(
  tabName = step_ids[[11]],
  h1("10.2 Unit of analysis bias"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Were treatments given dissolved in either food or drinking water?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("")
      )
    ),
    tabBox(
      title = tab_title("Were animals housed individually?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Were cages (not individual animals) compared statistically as the unit of analysis?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Unit-of-analysis errors might be present in animal studies, which could lead to
          inaccurate calculation of statistical measures. For example, if all mice in a cage
          are given a treatment in their diet, the experimental unit is the cage and not the
          individual animal.")
      )
    )
  )
)
animal_addition <- tabItem(
  tabName = step_ids[[12]],
  h1("10.3 Addition of animals"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = "Was it explicitly stated that animals were added to any cohort to replace missing ones?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Addition of animals to the control or experimental groups to replace drop-outs from
          the original sample is indicative of high risk of bias.")
      )
    )
  )
) 

# Assessment tool ---------------------------------------------------------


tool <- tabItem(
  tabName = "tool",
  h2("Risk of bias assessment"),
  br(),
  shiny::fluidPage(
    column(
      width = 5,
      br(),
      br(),
      lapply(tool_steps, make_row),
      br(),
      br(),
      actionLink("startover", "Start over")
    ),
    column(
      width = 7,
      shinysurveys::surveyOutput(df, 
                                 theme = NULL),
      br(),
      shinyjs::hidden(
        downloadButton(
          "downloadResponses","Download responses"
          )
        )
      )
    )
  )


# Data visualization ------------------------------------------------------

plots <- tabItem(
  tabName = "plots",
  h1("Risk of bias plots"),
  br(),
  column(
    width = 4,
    box(
      width = 12,
      # title = "Upload data",
      selectInput(
        inputId = "dataformat",
        label = "Select data format",
        choices = list("app"),
        # choices = list("app","SyRF"),
        selected = character(0)
      ),
      fileInput(
        inputId = "uploadfile", 
        label = "Upload csv file",
        accept = c(".csv"),
        multiple = TRUE
      ),
      uiOutput(
          "datamessage"
          ),
      br(),
      selectInput(
        inputId = "showPlotType",
        label = "Select type of plot",
        choices = list("Traffic light plot", "Summary plot"),
        selected = character(0)
      ),
      checkboxInput(
        inputId = "showColorBlind",
        label = "Color blind friendly"
      ),
      actionButton(
        inputId = "generateplot",
        label = "Generate plot"
      ),
      br(),
      br(),
      dropdown(
        right = FALSE,
        animate = FALSE,
        selectInput(
          inputId = "savePlotType",
          label = "Select type of plot output",
          choices = c("Traffic light", "Summary"),
          multiple = FALSE,
          selected = "Traffic light",
          width = "auto"
        ),
        selectInput(
          inputId = "formatplot",
          label = "Select format of plot output",
          choices = list("png","pdf","tiff"),
          multiple = FALSE,
          selected = ".png",
          width = "auto"
        ),
        checkboxInput(
          inputId = "saveColorBlind",
          label = "Color blind friendly"
        ),
        br(),
        br(),
        downloadButton('downloadPlot','Save'),
        # icon = icon("file-alt"),
        up = FALSE,
        label = "Save plot",
        size = "default",
        inputId = "saveplot"
      ),
      br(),
      actionButton(
        inputId = "helpUpload",
        label = "Help",
        icon = icon("info-circle")
      )
    )
  ),
  column(
    width = 6,
    plotOutput("robplot")
    )
  )



# training feature --------------------------------------------------------

practice <- tabItem(
  tabName = "practice",
  h1("Test your skills"),
  lorem::ipsum(paragraphs = 1)
)


           
         
         