
# Information section -----------------------------------------------------

about <- tabItem(
  tabName = "about",
  h1("Welcome!"),
  lorem::ipsum(paragraphs = 1),
  h2("How to use this app"),
  lorem::ipsum(paragraphs = 2)
)



# Sequence allocation -----------------------------------------------------

sequence_allocation <- tabItem(
  tabName = step_ids[[1]],
  h1("Sequence allocation"),
  "Sequence allocation refers to the allocation of animals to the experimental and 
  control groups. This should be adequately generated, but also adequately applied, with 
  appropriate randomization. This item assesses whether the methodology used to generate
  the allocation sequence is described in sufficient detail to allow an assessment 
  whether it should produce comparable groups. The following signaling questions may be
  used to guide assessment of this domain.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Did the authors compare two cohorts of the same genetic model?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Do the authors report random allocation to group?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Did the authors describe a random component in the sequence generation process?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Was the method chosen appropriate to achieve random sequence allocation?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        "Referring to a random number table or using a computer random number generator
        are adequate approaches to including a random component in the sequence generation
        process. Examples of a non-random approach may include: allocation by the investigator's
        preference/judgement, allocation based on the results of laboratory tests, allocation
        by availability of the intervention, sequence generated by some rule based on animal or
        cage number, and sequence generated by odd or even date of birth."
        )
      )
    )
  )


# Baseline characteristics ------------------------------------------------

baseline_characteristics <- tabItem(
  tabName = step_ids[[2]],
  h1("Baseline characteristics"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Do the authors report the baseline characteristics in the methods, results or supplements?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Are the groups similar at baseline with respect to age, sex and weight?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = tab_title("Did the authors adjust the statistical analyses for confounders?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)



# Allocation concealment --------------------------------------------------

allocation_concealment <- tabItem(
  tabName = step_ids[[3]],
  h1("Allocation concealment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Was the allocation (randomization) procedure described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Was sequence generation conducted by someone not involved in the experiment?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = tab_title("Was the allocation concealment appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Random housing ----------------------------------------------------------

random_housing <- tabItem(
  tabName = step_ids[[4]],
  h1("Random housing"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Was housing described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Were cages placed randomly within the housing facility?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)



# Blinding ----------------------------------------------------------------

blinded_conduct <- tabItem(
  tabName = step_ids[[5]],
  h1("Blinded conduct of the experiment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Random outcome assessment -----------------------------------------------

random_outcome <- tabItem(
  tabName = step_ids[[6]],
  h1("Random outcome assessment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is randomization mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Is the method of randomization described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Blinded outcome assessment ----------------------------------------------

blind_outcome <- tabItem(
  tabName = step_ids[[7]],
  h1("Blinded outcome assessment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)

# Attrition ---------------------------------------------------------------

incomplete_outcome <- tabItem(
  tabName = step_ids[[8]],
  h1("Incomplete outcome data"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is there a section specifically describing drop-outs or mortality?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Do the numbers of animals that started the experiment and were analysed match?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Are the number and the reason for drop-out/death specified and equally distributed per group?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Were missing data imputed using appropriate statistical methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Selective outcome reporting ---------------------------------------------

selective_reporting <- tabItem(
  tabName = step_ids[[9]],
  h1("Selective outcome reporting"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Was the study protocol available and published prior to the study results?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = "Were results reported for all experiments outlined in the methods section and is the study is free of explicitly unpublished results?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Do all the outcomes in the protocol and in the final report match or were deviations reported?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = "Were all pre-specified outcomes conducted and reported as planned or were deviations explained?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Other bias --------------------------------------------------------------

funder_influence <- tabItem(
  tabName = step_ids[[10]],
  h1("Inappropriate influence of funders"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Were sources of funding reported?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Did the authors report a conflict of interest?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)

analysis_unit <- tabItem(
  tabName = step_ids[[11]],
  h1("Unit of analysis bias"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Were treatments given dissolved in either food or drinking water?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Were animals housed individually?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = "Were cages (not individual animals) compared statistically as the unit of analysis?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)
animal_addition <- tabItem(
  tabName = step_ids[[12]],
  h1("Addition of animals"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = "Was it explicitly stated that animals were added to any cohort to replace missing ones?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
) 

# Assessment tool ---------------------------------------------------------


tool <- tabItem(
  tabName = "tool",
  h2("Risk of bias assessment"),
  shiny::fluidPage(
    column(
      width = 4,
      br(),
      lapply(tool_steps, make_row),
      br(),
      br(),
      actionLink("startover", "Start over")
    ),
    column(
      width = 6,
      shinysurveys::surveyOutput(df, 
                                 theme = NULL),
      br(),
      shinyjs::hidden(
        downloadButton(
          "downloadResponses","Download responses"
          )
        )
      ),
    column(
      width = 3
      )
    )
  )


# Data visualization ------------------------------------------------------

plots <- tabItem(
  tabName = "plots",
  h1("Risk of bias plots"),
  br(),
  fluidRow(
    column(
      width = 5,
      box(
        # title = "Upload data",
        selectInput(
          inputId = "dataformat",
          label = "Select data format",
          choices = list("app","SyRF"),
          selected = character(0)
          ),
        fileInput(
          inputId = "uploadfile", 
          label = "Upload csv file",
          accept = c(".csv"),
          multiple = TRUE
        ),
        selectInput(
          inputId = "showPlotType",
          label = "Select type of plot",
          choices = list("Traffic light plot", "Summary plot"),
          selected = character(0)
        ),
        checkboxInput(
          inputId = "showColorBlind",
          label = "Color blind friendly"
        ),
        actionButton(
          inputId = "generateplot",
          label = "Generate plot"
        ),
        br(),
        br(),
        dropdown(
          right = FALSE,
          animate = FALSE,
          selectInput(
            inputId = "savePlotType",
            label = "Select type of plot output",
            choices = c("Traffic light", "Summary"),
            multiple = FALSE,
            selected = "Traffic light",
            width = "auto"
          ),
          selectInput(
            inputId = "formatplot",
            label = "Select format of plot output",
            choices = list("png","pdf","tiff"),
            multiple = FALSE,
            selected = ".png",
            width = "auto"
          ),
          checkboxInput(
            inputId = "saveColorBlind",
            label = "Color blind friendly"
          ),
          br(),
          br(),
          downloadButton('downloadPlot','Save'),
          # icon = icon("file-alt"),
          up = FALSE,
          label = "Save plot",
          size = "default",
          inputId = "saveplot"
        )
      )
    ),
    column(
      width = 6,
        plotOutput("robplot")
      )
    )
  )



# training feature --------------------------------------------------------

practice <- tabItem(
  tabName = "practice",
  h1("Test your skills"),
  lorem::ipsum(paragraphs = 1)
)


           
         
         