
# Information section -----------------------------------------------------

about <- tabItem(
  tabName = "about",
  h1("Welcome!"),
  lorem::ipsum(paragraphs = 1),
  h2("How to use this app"),
  lorem::ipsum(paragraphs = 2)
)



# Sequence allocation -----------------------------------------------------

sequence_allocation <- tabItem(
  tabName = step_ids[[1]],
  h1("Sequence allocation"),
  "Sequence allocation refers to the allocation of animals to the experimental and 
  control groups. This should be adequately generated, but also adequately applied, with 
  appropriate randomization. This item assesses whether the methodology used to generate
  the allocation sequence is described in sufficient detail to allow an assessment 
  whether it should produce comparable groups. The following signaling questions may be
  used to guide assessment of this domain.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Did the authors compare two cohorts of the same genetic model?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("The comparison of cohorts of different genetic models, irrespective of subsequent 
        randomization procedures, indicates a high risk of bias.")
      )
    ),
    tabBox(
      title = ("Do the authors report random allocation to group?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If allocation to group is not reported to be random, it is unclear whether groups were
          randomized, even if this was part of experimental procedures.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Did the authors describe a random component in the sequence generation process?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("It is generally not sufficient to mention randomization alone, without describing
          the method used to achieve random sequence allocation.")
      )
    ),
    tabBox(
      title = ("Was the method chosen appropriate to achieve random sequence allocation?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Referring to a random number table or using a computer random number generator
        are adequate approaches to including a random component in the sequence generation
        process. Examples of a non-random approach may include: allocation by the investigator's
        preference/judgement, allocation based on the results of laboratory tests, allocation
        by availability of the intervention, sequence generated by some rule based on animal or
        cage number, and sequence generated by odd or even date of birth.")
        )
      )
    )
  )


# Baseline characteristics ------------------------------------------------

baseline_characteristics <- tabItem(
  tabName = step_ids[[2]],
  h1("Baseline characteristics"),
  "This item refers to the distribution of relevant baseline characteristics for the different
  treatment groups. Depending on whether this distribution is balanced or unequal, 
  different actions are recommended to investigators in order to avoid bias.
  It is important to note that the number and type of baseline characteristics 
  are dependent on the review question. Before starting their risk of bias assessment, 
  reviewers need to discuss which baseline characteristics need to be comparable between the groups.
  A description of baseline characteristics and/or confounders usually contains: (1) the sex, age and 
  weight of the animals, and (2) baseline values of the outcomes which are of interest in the study/",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Do the authors report the baseline characteristics (age, sex AND weight) 
               in the methods, results or supplements?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("If any of the predefined baseline characteristics are not described anywhere in 
        the study, the risk of bias remains unclear. This holds even if the authors state 
        that groups did not differ at baseline.")
      )
    ),
    tabBox(
      title = ("Are the groups similar at baseline with respect to age, sex and weight?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Observed differences in baseline characteristics between groups might point to
          high risk of bias if not properly accounted for in the analysis.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Did the authors adjust the statistical analyses for confounders?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In the case of unequal distribution of baseline characteristics between groups, the
        risk of bias is declared low if the investigators adjust for it in the statistical
        analyses, and high if not.")
      )
    )
  )
)



# Allocation concealment --------------------------------------------------

allocation_concealment <- tabItem(
  tabName = step_ids[[3]],
  h1("Allocation concealment"),
  "Allocation concealment refers to the blinding of participants and personnel, which 
  can be a source of performance bias. In the case of animal studies, this refers predominantly 
  to the personnel involved in the experiments. This includes both researchers, as well as animal
  caregivers, as the handling of animals during the study while knowing the treatment condition
  could cause behavioral changes influencing the study results.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Was the allocation (randomization) procedure described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Lack of information on how the procedure of sequence allocation occurred is indicative
          of unclear risk of bias in this domain.")
      )
    ),
    tabBox(
      title = ("Was sequence generation conducted by someone not involved in the experiment?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In cases where sequence allocation is done by third-parties not involved in the
          experimental study, concealment is deemed appropriate and indicates a low risk of 
          performance bias.")
      )
    )
  ),
  fluidRow(
    tabBox(
      title = ("Was the allocation concealment appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("In addition to third-party group allocation, another example of appropriate concealment
          includes the use of properly safeguarded envelopes e.g. sequentially numbered
          opaque, sealed envelopes. On the other hand, inadequare approaches to concealment include: 
          open randomization schedule, envelopes without proper safeguard, alternation or rotation,
          allocation based on date of birth or animal number, or any other explicitly unconcealed
          procedure of a non-random approach.")
      )
    )
  )
)


# Random housing ----------------------------------------------------------

random_housing <- tabItem(
  tabName = step_ids[[4]],
  h1("Random housing"),
  "This item refers to the housing conditions of animals during the experiment, an important 
  element of adequately blinding the animal caregivers and investigators. 
  As housing conditions (such as lighting, humidity,  temperature, etc.) are known to 
  influence study outcomes (such as certain biochemical parameters and behavior), 
  it is important that the housing of these animals is randomized or, in other words, 
  comparable between the experimental groups in order to reduce the risk of performance bias.",
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Was housing described in the methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("Lack of information on the housing conditions of animals during the
          study signals an unclear risk of bias, as it remains difficult to ascertain
          if these were handled appropriately.")
      )
    ),
    tabBox(
      title = ("Were cages placed randomly within the housing facility?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        p("For example, animals from different treatment groups should not be housed 
        per group on different shelves or in different rooms as the animals on the 
        top shelf experience a higher room temperature than animals on the lowest shelf, 
        and the temperature of the room may influence the toxicity of pharmacological 
        agents. When cages are not placed randomly (e.g., when animals are housed per group 
        on different shelves), moreover, it is possible for the investigator to predict 
        the allocation of the animals to the various groups, which would indicate 
        performance bias.")
      )
    )
  )
)



# Blinding ----------------------------------------------------------------

blinded_conduct <- tabItem(
  tabName = step_ids[[5]],
  h1("Blinded conduct of the experiment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Random outcome assessment -----------------------------------------------

random_outcome <- tabItem(
  tabName = step_ids[[6]],
  h1("Random outcome assessment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is randomization mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Is the method of randomization described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Blinded outcome assessment ----------------------------------------------

blind_outcome <- tabItem(
  tabName = step_ids[[7]],
  h1("Blinded outcome assessment"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Is blinding mentioned?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Is the method of blinding described appropriate?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)

# Attrition ---------------------------------------------------------------

incomplete_outcome <- tabItem(
  tabName = step_ids[[8]],
  h1("Incomplete outcome data"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = space_after("Is there a section specifically describing drop-outs or mortality?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = ("Do the numbers of animals that started the experiment and were analysed match?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Are the number and the reason for drop-out/death specified and equally distributed per group?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = space_after("Were missing data imputed using appropriate statistical methods?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Selective outcome reporting ---------------------------------------------

selective_reporting <- tabItem(
  tabName = step_ids[[9]],
  h1("Selective outcome reporting"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Was the study protocol available and published prior to the study results? "),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = "Were results reported for all experiments outlined in the methods section and is the study is free of explicitly unpublished results?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Do all the outcomes in the protocol and in the final report match or were deviations reported?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = "Were all pre-specified outcomes conducted and reported as planned or were deviations explained?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)


# Other bias --------------------------------------------------------------

funder_influence <- tabItem(
  tabName = step_ids[[10]],
  h1("Inappropriate influence of funders"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = tab_title("Were sources of funding reported?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Did the authors report a conflict of interest?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)

analysis_unit <- tabItem(
  tabName = step_ids[[11]],
  h1("Unit of analysis bias"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = ("Were treatments given dissolved in either food or drinking water?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    ),
    tabBox(
      title = tab_title("Were animals housed individually?"),
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  ),
  fluidRow(
    tabBox(
      title = "Were cages (not individual animals) compared statistically as the unit of analysis?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
)
animal_addition <- tabItem(
  tabName = step_ids[[12]],
  h1("Addition of animals"),
  lorem::ipsum(paragraph = 1),
  br(),
  br(),
  br(),
  fluidRow(
    tabBox(
      title = "Was it explicitly stated that animals were added to any cohort to replace missing ones?",
      width = 6,
      side = "right",
      selected = "Description",
      tabPanel(
        "Examples",
        lorem::ipsum(sentences = 2)
      ),
      tabPanel(
        "Description",
        lorem::ipsum(paragraphs = 1)
      )
    )
  )
) 

# Assessment tool ---------------------------------------------------------


tool <- tabItem(
  tabName = "tool",
  h2("Risk of bias assessment"),
  br(),
  shiny::fluidPage(
    column(
      width = 5,
      br(),
      br(),
      lapply(tool_steps, make_row),
      br(),
      br(),
      actionLink("startover", "Start over")
    ),
    column(
      width = 7,
      shinysurveys::surveyOutput(df, 
                                 theme = NULL),
      br(),
      shinyjs::hidden(
        downloadButton(
          "downloadResponses","Download responses"
          )
        )
      )
    )
  )


# Data visualization ------------------------------------------------------

plots <- tabItem(
  tabName = "plots",
  h1("Risk of bias plots"),
  br(),
  column(
    width = 4,
    box(
      width = 12,
      # title = "Upload data",
      selectInput(
        inputId = "dataformat",
        label = "Select data format",
        choices = list("app"),
        # choices = list("app","SyRF"),
        selected = character(0)
      ),
      fileInput(
        inputId = "uploadfile", 
        label = "Upload csv file",
        accept = c(".csv"),
        multiple = TRUE
      ),
      uiOutput(
          "datamessage"
          ),
      br(),
      selectInput(
        inputId = "showPlotType",
        label = "Select type of plot",
        choices = list("Traffic light plot", "Summary plot"),
        selected = character(0)
      ),
      checkboxInput(
        inputId = "showColorBlind",
        label = "Color blind friendly"
      ),
      actionButton(
        inputId = "generateplot",
        label = "Generate plot"
      ),
      br(),
      br(),
      dropdown(
        right = FALSE,
        animate = FALSE,
        selectInput(
          inputId = "savePlotType",
          label = "Select type of plot output",
          choices = c("Traffic light", "Summary"),
          multiple = FALSE,
          selected = "Traffic light",
          width = "auto"
        ),
        selectInput(
          inputId = "formatplot",
          label = "Select format of plot output",
          choices = list("png","pdf","tiff"),
          multiple = FALSE,
          selected = ".png",
          width = "auto"
        ),
        checkboxInput(
          inputId = "saveColorBlind",
          label = "Color blind friendly"
        ),
        br(),
        br(),
        downloadButton('downloadPlot','Save'),
        # icon = icon("file-alt"),
        up = FALSE,
        label = "Save plot",
        size = "default",
        inputId = "saveplot"
      ),
      br(),
      actionButton(
        inputId = "helpUpload",
        label = "Help",
        icon = icon("info-circle")
      )
    )
  ),
  column(
    width = 6,
    plotOutput("robplot")
    )
  )



# training feature --------------------------------------------------------

practice <- tabItem(
  tabName = "practice",
  h1("Test your skills"),
  lorem::ipsum(paragraphs = 1)
)


           
         
         